# Generated by Django 4.0.5 on 2022-06-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Published_date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
    ]
